# Generated by Django 4.2.9 on 2024-03-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="accountType",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="account.accounttype",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="documentGroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="account.documentgroup",
            ),
        ),
    ]
