# Generated by Django 4.2.9 on 2024-03-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_accounttype_alter_account_documentgroup"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="accountType",),
    ]
