# Generated by Django 4.2.9 on 2024-03-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_account_accounttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttype",
            name="accountType",
            field=models.CharField(
                choices=[("GL", "Gelir"), ("GD", "Gider")], max_length=2
            ),
        ),
    ]
