# Generated by Django 4.2.9 on 2024-04-17 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_documenttype_accounttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={"verbose_name_plural": "Banka", "ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={"verbose_name_plural": "Document", "ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="PayType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={"verbose_name_plural": "PayType", "ordering": ("name",),},
        ),
        migrations.AddField(
            model_name="supplier",
            name="isCustomer",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="isSupplier",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="banka",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="account.banka",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="account.document",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="payType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="account.paytype",
            ),
        ),
    ]
