# Generated by Django 4.2.9 on 2024-03-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("area", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="areaType",
            field=models.CharField(
                choices=[
                    ("T", "Tente"),
                    ("C", "Caravan"),
                    ("H", "Room"),
                    ("N", "Motarea"),
                ],
                max_length=1,
            ),
        ),
    ]
